### PR TITLE
Add custom navbar guide

### PR DESCRIPTION
**Pull request by BernatBC**
Adds guide for custom navbar title (hugo-toha/toha/pull/921)

### CODE REVIEW

**Review by hossainemruz — APPROVED** [review]
Thank you @BernatBC

**Comment by niltied** [comment]
Hi @BernatBC,

Maybe you'll go faster than me. Is it possible that you also make the modification for the `index.fr.md` file as follow ? 

```yaml
navBarTitle: "Titre"
```

Thank U for you help

**Comment by BernatBC** [comment]
Hi @niltied,
I could do it, but the translation might not be good enough. If you want, you can send me the translation. Otherwise, in a couple of days I could try doing it.

**Comment by niltied** [comment]
Re,

If you translate the `index.md` file, for English, it looks like this :
```yaml
navBarTitle: "Title"
```
So, for French, it’s will be :
```yaml
navBarTitle: "Ti**tr**e"
```
There are no other translations.

**Comment by BernatBC** [comment]
Ok, what about the following?
```md
### Change Navbar Title
To change the title appearing on the navbar, you can modify `site.yaml` file. By defauly, the title corresponds to the website name. You can add the following line:
```

**Comment by niltied** [comment]
Hi @BernatBC,

So, it will be : "Pour changer le titre qui apparaît sur la barre de navigation, vous pouvez midifier le fichier `site.yaml`. Par defaut, le titre correpond au nom du site. Vous pouvez ajouter la ligne suivante:"

**Pull request merged**
