### PR TITLE
Little fix from PR #938

### PR DESCRIPTION
**Pull request by niltied**
Hi @hossainemruz,

How are you ? I'm fine and congratulation for Toha v4.5.0 :). Nice release :)

I just saw in the Toha v4.5.0 release note that Umami is now supported. That's great ! But I saw some omissions in the documentation part related to Pull Request #938.

So I made improvements:

- In the `index.md` file : Addition of acronyms and the Umami link at the start of the article.
- In the `index.fr.md` file : French post is up to date with English post.
- In the `index.es.md` file : Just added the Umami link at the beginning of the post. If possible @BernatBC, if you can update the Spanish article to be fully synchronized. It will be perfect.

That's all !

See you later,

### CODE REVIEW

**Comment by BernatBC** [comment]
Hi @niltied 
Thank you for reminding me to translate this section to spanish. I've just added it.

Btw, I think we should add some method in order to know which translations are outdated. This could be a table indicating which pages are not updated or something else. What do you think @hossainemruz?

**Comment by niltied** [comment]
Hi @BernatBC,

You are welcome. I agree with you about checking which translations are outdated. This must be necessary if we want to guarantee synchronization between the different translated docs. 

@hossainemruz ?

**Comment by BernatBC** [comment]
I've researched a little bit, and many open source projects use platforms like [Weblate](https://weblate.org/) or [Crowdin](https://crowdin.com/). Those are free for open source software, but probably we don't need that complex tools.

**Review by hossainemruz — APPROVED** [review]
Thank you @niltied.

**Pull request merged**
